import { createFileRoute } from "@tanstack/react-router";
import { X, ZoomIn } from "lucide-react";
import { useEffect, useState } from "react";
import { ButtonLink } from "@/components/button";
import { PageHero, SectionHeading } from "@/components/site-layout";
import { pageHead } from "@/components/seo";
import { galleryImages } from "@/data/site-data";
export const Route=createFileRoute("/gallery")({head:()=>pageHead("Past Tour Gallery | BT New Adventure Tours","See real moments from previous BT New Adventure Tours journeys and cultural experiences in South Africa.","/gallery"),component:Gallery});
function Gallery(){const [selected,setSelected]=useState<number|null>(null); useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]); const selectedImage=selected===null?undefined:galleryImages[selected]; return <><PageHero eyebrow="Our gallery" title="Real Journeys. Shared Moments." text="A selection of photographs from tours and experiences we have hosted before." image={galleryImages[4].src}/><section className="py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Past tours" title="Moments from the road" text="Every group and every journey is different. These photographs reflect the people, places and experiences shared along the way."/><div className="mt-12 columns-1 gap-4 sm:columns-2 lg:columns-3">{galleryImages.map((img,i)=><button type="button" key={img.src} onClick={()=>setSelected(i)} className="group relative mb-4 block w-full overflow-hidden text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><img src={img.src} alt={img.alt} loading="lazy" className="w-full object-cover transition-transform duration-500 group-hover:scale-105"/><span className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-navy/85 p-4 text-sm font-bold text-navy-foreground"><span>{img.caption}</span><ZoomIn size={18}/></span></button>)}</div><div className="mt-12 text-center"><ButtonLink to="/request-quote">Plan Your Own Experience</ButtonLink></div></div></section>{selectedImage&&<div role="dialog" aria-modal="true" aria-label="Gallery image" onClick={()=>setSelected(null)} className="fixed inset-0 z-[80] flex items-center justify-center bg-navy/95 p-4"><button type="button" onClick={()=>setSelected(null)} aria-label="Close image" className="absolute right-5 top-5 flex size-11 items-center justify-center rounded-full bg-background text-foreground"><X/></button><figure onClick={e=>e.stopPropagation()} className="max-w-5xl"><img src={selectedImage.src} alt={selectedImage.alt} className="max-h-[80vh] w-auto object-contain"/><figcaption className="bg-background p-3 text-center text-sm font-bold">{selectedImage.caption}</figcaption></figure></div>}</>}
